[build]
  command = "npm run build"
  publish = "dist/public" # Assuming your client-side Vite build outputs to dist/public

[functions]
  directory = "dist" # Your server/index.ts is bundled to dist/index.js
  node_bundler = "esbuild" # Explicitly tell Netlify to use esbuild for functions
